name: Check Krishak Bandhu Status

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# এই লাইনটি রানারকে সরাসরি Node.js 24 ব্যবহার করতে বাধ্য করবে
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python script.py
        
